10-31 15:10:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "TEST" not found; SQL statement:
INSERT INTO TEST (NAME, EMAIL, ADDRESS, TELEPHONE) VALUES('TEST TEST', 'email@email.email', 'address address address', 123456789) [42102-176]
10-31 15:15:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP TABLE CONTACT

CREATE[*] TABLE CONTACT(ID INT PRIMARY KEY  AUTO_INCREMENT, NAME VARCHAR(255), EMAIL VARCHAR(255), ADDRESS VARCHAR(255), TELEPHONE VARCHAR(255))"; SQL statement:
DROP TABLE CONTACT

CREATE TABLE CONTACT(ID INT PRIMARY KEY  AUTO_INCREMENT, NAME VARCHAR(255), EMAIL VARCHAR(255), ADDRESS VARCHAR(255), TELEPHONE VARCHAR(255)) [42000-176]
2015-10-31 15:18:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "contact_id" not found [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3129)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3217)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:339)
	at HealthCheck.APIHealthCheck.dao.ContactDAOImpl$1.mapRow(ContactDAOImpl.java:53)
	at HealthCheck.APIHealthCheck.dao.ContactDAOImpl$1.mapRow(ContactDAOImpl.java:47)
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:92)
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:1)
	at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:446)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:396)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:456)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:464)
	at HealthCheck.APIHealthCheck.dao.ContactDAOImpl.list(ContactDAOImpl.java:47)
	at HealthCheck.APIHealthCheck.controller.HomeController.listContact(HomeController.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:212)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:126)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:96)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:617)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:578)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:900)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:827)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2503)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
10-31 15:20:13 database: close
org.h2.message.DbException: IO Exception: "java.io.EOFException"; "C:/Users/User/Desktop/Java/DB/HealthCheckDB.h2.db" [90031-176]
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.convertIOException(DbException.java:329)
	at org.h2.store.FileStore.readFully(FileStore.java:276)
	at org.h2.store.PageStore.readPage(PageStore.java:1326)
	at org.h2.store.PageStore.getPage(PageStore.java:750)
	at org.h2.store.PageStreamTrunk$Iterator.next(PageStreamTrunk.java:252)
	at org.h2.store.PageLog.free(PageLog.java:214)
	at org.h2.store.PageStore.compact(PageStore.java:499)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1301)
	at org.h2.engine.Database.close(Database.java:1251)
	at org.h2.engine.Database.removeSession(Database.java:1122)
	at org.h2.engine.Session.close(Session.java:672)
	at org.h2.jdbc.JdbcConnection.close(JdbcConnection.java:383)
	at org.h2.server.web.WebApp.logout(WebApp.java:984)
	at org.h2.server.web.WebApp.process(WebApp.java:216)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:171)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.EOFException"; "C:/Users/User/Desktop/Java/DB/HealthCheckDB.h2.db" [90031-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 19 more
Caused by: java.io.EOFException
	at org.h2.store.fs.FileUtils.readFully(FileUtils.java:347)
	at org.h2.store.FileStore.readFully(FileStore.java:274)
	... 16 more
11-01 14:47:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "Mr. SIR" not found; SQL statement:
INSERT INTO CONTACT (NAME, EMAIL, ADDRESS, TELEPHONE) VALUES ("Mr. SIR", "bla", "Address", "0981234") [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
11-01 14:48:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "bla" not found; SQL statement:
INSERT INTO CONTACT (NAME, EMAIL, ADDRESS, TELEPHONE) VALUES ('Mr. SIR', "bla", "Address", "0981234") [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148)
	at org.h2.command.dml.Insert.prepare(Insert.java:271)
	at org.h2.command.Parser.prepareCommand(Parser.java:248)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
11-01 14:49:39 database: close
org.h2.message.DbException: IO Exception: "java.io.EOFException"; "C:/Users/User/Desktop/Java/DB/HealthCheckDB.h2.db" [90031-176]
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.convertIOException(DbException.java:329)
	at org.h2.store.FileStore.readFully(FileStore.java:276)
	at org.h2.store.PageStore.readPage(PageStore.java:1326)
	at org.h2.store.PageStore.getPage(PageStore.java:750)
	at org.h2.store.PageStreamTrunk$Iterator.next(PageStreamTrunk.java:252)
	at org.h2.store.PageLog.free(PageLog.java:214)
	at org.h2.store.PageStore.compact(PageStore.java:499)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1301)
	at org.h2.engine.Database.close(Database.java:1251)
	at org.h2.engine.Database.removeSession(Database.java:1122)
	at org.h2.engine.Session.close(Session.java:672)
	at org.h2.jdbc.JdbcConnection.close(JdbcConnection.java:383)
	at org.h2.server.web.WebApp.logout(WebApp.java:984)
	at org.h2.server.web.WebApp.process(WebApp.java:216)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:171)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.EOFException"; "C:/Users/User/Desktop/Java/DB/HealthCheckDB.h2.db" [90031-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 19 more
Caused by: java.io.EOFException
	at org.h2.store.fs.FileUtils.readFully(FileUtils.java:347)
	at org.h2.store.FileStore.readFully(FileStore.java:274)
	... 16 more
11-10 14:03:37 database: close
org.h2.message.DbException: IO Exception: "java.io.EOFException"; "C:/Users/User/Desktop/Java/Workspace/APIHealthCheck/DB/HealthCheckDB.h2.db" [90031-176]
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.convertIOException(DbException.java:329)
	at org.h2.store.FileStore.readFully(FileStore.java:276)
	at org.h2.store.PageStore.readPage(PageStore.java:1326)
	at org.h2.store.PageStore.getPage(PageStore.java:750)
	at org.h2.store.PageStreamTrunk$Iterator.next(PageStreamTrunk.java:252)
	at org.h2.store.PageLog.free(PageLog.java:214)
	at org.h2.store.PageStore.compact(PageStore.java:499)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1301)
	at org.h2.engine.Database.close(Database.java:1251)
	at org.h2.engine.Database.removeSession(Database.java:1122)
	at org.h2.engine.Session.close(Session.java:672)
	at org.h2.jdbc.JdbcConnection.close(JdbcConnection.java:383)
	at org.h2.server.web.WebApp.logout(WebApp.java:984)
	at org.h2.server.web.WebApp.process(WebApp.java:216)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:171)
	at org.h2.server.web.WebThread.process(WebThread.java:138)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.EOFException"; "C:/Users/User/Desktop/Java/Workspace/APIHealthCheck/DB/HealthCheckDB.h2.db" [90031-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	... 19 more
Caused by: java.io.EOFException
	at org.h2.store.fs.FileUtils.readFully(FileUtils.java:347)
	at org.h2.store.FileStore.readFully(FileStore.java:274)
	... 16 more
11-10 14:41:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "TABLE" not found; SQL statement:
DELETE TABLE API [42102-176]
11-12 15:18:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "PERSON_ID" not found; SQL statement:
CREATE TABLE PERSONAL_API (PERSONAL_API_ID INT PRIMARY KEY, FOREIGN KEY(PERSON_ID) REFERENCES PERSON(PERSON_ID), FOREIGN KEY(API_ID) REFERENCES API(API_ID)) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.table.Table.getColumn(Table.java:637)
	at org.h2.table.IndexColumn.mapColumns(IndexColumn.java:75)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:198)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:73)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:170)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:186)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
11-12 15:20:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "PERSON_ID" not found; SQL statement:
ALTER TABLE PERSONAL_API ADD FOREIGN KEY ( PERSON_ID ) REFERENCES PERSON( PERSON_ID) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.table.Table.getColumn(Table.java:637)
	at org.h2.table.IndexColumn.mapColumns(IndexColumn.java:75)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:198)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:73)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:186)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
11-12 15:21:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: ")"; SQL statement:
ALTER TABLE PERSONAL_API ADD ( PERSON_ID ) [50004-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3963)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3826)
	at org.h2.command.Parser.parseAlterTableAddColumn(Parser.java:5472)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5274)
	at org.h2.command.Parser.parseAlter(Parser.java:4689)
	at org.h2.command.Parser.parsePrepared(Parser.java:333)
	at org.h2.command.Parser.parse(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Unknown Source)
11-13 16:25:20 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "TEST" not found; SQL statement:
INSERT INTO TEST(name) VALUES('First API') [42102-176]
11-13 16:25:20 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "TEST" not found; SQL statement:
INSERT INTO TEST(name) VALUES('Second API') [42102-176]
11-13 16:25:20 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "TEST" not found; SQL statement:
INSERT INTO TEST(name) VALUES('Third API') [42102-176]
